#!/bin/bash
## kola:
##   exclusive: true
##   description: Verify /usr/share/licenses/fedora-coreos-config/LICENSE exists.
##   tags: needs-internet

set -xeuo pipefail

# shellcheck disable=SC1091
. "$KOLA_EXT_DATA/commonlib.sh"

curl http://192.168.100.1:8000/config
if ! test -f /usr/share/licenses/fedora-coreos-config/LICENSE; then
    fatal missing LICENSE
fi
ok LICENSE
